### ISSUE TITLE
Operador Div

### ISSUE THREAD

**Issue by divirjo** [FilosoDev/Mini_manual_VISUALG#1]
Olá, Flávio. 

Ainda estou aprendendo Github, não sei se estou fazendo corretamente, mas entendo ser interessante adicionar o operador DIV na relação de operadores aritméticos:

Divisão (quociente) → Divisão de um valor, recebendo somente o valor do quociente
Exemplo: total := num1 \ num2

ps. sou aluno do Senai, estou assistindo os vídeos que você disponibilizou no AVA.

**Comment by FilosoDev** [comment]
Bem lembrado!

Eu posso alterar por aqui ou...

Você pode fazer um fork desse projeto, alterar na sua máquina e enviar um pull request para que eu aceite a sua modificação.

Quer tentar?

Qualquer problema, me chame no AVA. Procure nos contatos "Arthur Antunes Ferreira", tudo bem?

abs

**Comment by divirjo** [comment]
Combinado, 
Até o fim de semana eu tento o pull request, qq coisa eu te chamo.
